# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(442, 250)
        self.label = QtWidgets.QLabel(Calculator)
        self.label.setGeometry(QtCore.QRect(10, 10, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Calculator)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Result_Label = QtWidgets.QLabel(Calculator)
        self.Result_Label.setGeometry(QtCore.QRect(20, 140, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Result_Label.setFont(font)
        self.Result_Label.setText("")
        self.Result_Label.setObjectName("Result_Label")
        self.Calcualte_Button = QtWidgets.QPushButton(Calculator)
        self.Calcualte_Button.setGeometry(QtCore.QRect(10, 180, 421, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Calcualte_Button.setFont(font)
        self.Calcualte_Button.setObjectName("Calcualte_Button")
        self.LineEdit = QtWidgets.QLineEdit(Calculator)
        self.LineEdit.setGeometry(QtCore.QRect(290, 79, 131, 31))
        self.LineEdit.setObjectName("LineEdit")
        
        self.Calcualte_Button.clicked.connect(self.Click)

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)
        
    def Click(self):
        self.Result_Label.setText("Result is " + self.Calculate_Binary())
    
    def Calculate_Binary(self):
        number1 = self.LineEdit.text()
        number1 = number1[::-1]
        l1 = []
        number2 = 0
        for i in number1:
            l1.append(i)
            
        for count, ele in enumerate(l1):
            ele = int(ele)
            
            if ele == 1:
                number2 += 2 ** count
        
        return str(number2)
            

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Binary Calculating System"))
        self.label.setText(_translate("Calculator", "Binary Calculating System"))
        self.label_2.setText(_translate("Calculator", "Enter the binary number"))
        self.Calcualte_Button.setText(_translate("Calculator", "Calculate"))

if __name__ == "__main__":
    import sys
    app= QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Calculator()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())